services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: NameNode
    hostname: NameNode
    ports:
      - "9870:9870"  # Web UI
      - "8020:8020"  # Internal communication
    environment:
      - CLUSTER_NAME=hdfscluster
    volumes:
      - namenode-data:/hadoop/dfs/name
    networks:
      - kafka-spark-net

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: DataNode1
    hostname: DataNode1
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - datanode1-data:/hadoop/dfs/data
    networks:
      - kafka-spark-net

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: DataNode2
    hostname: DataNode2
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - datanode2-data:/hadoop/dfs/data
    networks:
      - kafka-spark-net

  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: DataNode3
    hostname: DataNode3
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    volumes:
      - datanode3-data:/hadoop/dfs/data
    networks:
      - kafka-spark-net

networks:
  kafka-spark-net:
    external: true

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:
  datanode3-data: